// <auto-generated />
namespace Datos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Creacionconstructorhecho : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Creacionconstructorhecho));
        
        string IMigrationMetadata.Id
        {
            get { return "201805231533306_Creacion constructor hecho"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
