// <auto-generated />
namespace Datos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Tablapropiedaddenavegacionhecho_persona : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Tablapropiedaddenavegacionhecho_persona));
        
        string IMigrationMetadata.Id
        {
            get { return "201805212310499_Tabla propiedad de navegacion hecho_persona"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
