// <auto-generated />
namespace Datos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Tablaverbalabreviado : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Tablaverbalabreviado));
        
        string IMigrationMetadata.Id
        {
            get { return "201805201546280_Tabla verbal abreviado"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
