// <auto-generated />
namespace Datos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Tablaverbalabreviadoajustes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Tablaverbalabreviadoajustes));
        
        string IMigrationMetadata.Id
        {
            get { return "201805201809433_Tabla verbal abreviado ajustes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
